select T2.RDB$RELATION_NAME, T2.RDB$FIELD_NAME, T1.RDB$FIELD_NAME INDEX_NAME,
T1.RDB$FIELD_LENGTH, T1.RDB$COLLATION_ID, T1.RDB$CHARACTER_SET_ID

from RDB$FIELDS T1, RDB$RELATION_FIELDS T2

where T1.RDB$FIELD_TYPE = 37 and
      T2.RDB$VIEW_CONTEXT is null and
      T1.RDB$FIELD_NAME = T2.RDB$FIELD_SOURCE and
      not T2.RDB$RELATION_NAME like 'RDB$%' and
      not T2.RDB$RELATION_NAME like 'MON$%'

order by T2.RDB$RELATION_NAME

